<div> 
  <h1><a name="_Toc132145324">How to Use XGene 360</a></h1> 
  <a name="index"></a>
  <h2><a name="_Toc132145325">General Information</a></h2> 
  <a name="login"></a>
  <h3><a name="_Toc132145326">Login</a></h3> 
  <p>To login to the application:</p> 
  <ol> 
    <li>Enter a CWL username.</li> 
    <li>Enter a password.</li> 
    <li>Press the "Login" button.</li> 
    <li>If the user is valid, the user will log into their account.</li> 
    <li>If the user is not valid, an error message will be produced and the user will be prompted to enter the information again.</li> 
  </ol> 
  <p>Only users with valid UBC CWL account are allowed to access the application.</p>
  <p>If user desires to have access to the application, the user will have to contact either a professor or site administrator of the application.</p> 
  <a name="logout"></a>
  <h3><a name="_Toc132145327">Logout</a></h3> 
  <p>To logout of the application while logged in:</p> 
  <ol> 
    <li>Click the "LOGOUT" link on the upper-right corner of the page. </li> 
    <li>The user will be logged out and brought back to the login page.</li> 
  </ol> 
  <p>Note that the user can log out at any time while logged in.</p> 
  <h3><a name="_Toc132145329">Navigation Bar</a></h3> 
  <p>The navigation bar on the top will hold links to relevant pages such as managing courses or viewing problems.</p> 
  <h3><a name="_Toc132145330">Sorting</a></h3> 
  <p>Any list of data has the capability of sorting the contents alphabetically and numerically by a header name. For example, a listing of problems can be sorted by the problem name, course that is associated with the problem, starting date, due date and breeding history.</p> 
  <p>To be able to sort data by a header type, just click on the header (which is displayed as a link). An arrow will appear on the right of the header name to indicate whether the sort is ascending (up arrow) or descending (down arrow). To toggle between ascending and descending, simply click the header name again. </p> 
  <h3><a name="_Toc132145331">Selecting</a></h3> 
  <p>A specific entry can be selected from a list of entry data in several ways:</p> 
  <ul>
    <li>Having the cursor hover over an entry may show that the entry is a link. If the link is selected, the user will be led to a page containing specific information about that particular entry</li> 
    <li>For most lists of data, the rightmost column will be a column of checkboxes. The checkboxes can be used to select several entries in order to perform operations such as deleting several courses. The header checkbox allows the user to select or deselect all entry checkboxes.</li>
  </ul> 
  <h2><a name="_Toc132145332">Problems Management</a></h2> 
  <p>Problems are the heart of the application. This is where the professor can assign students a group of plants for the student to breed and solve the problem.</p> 
  <h3><a name="_Toc132145333">Viewing Problems Listing</a></h3> 
  <p>To view a list of problems:</p> 
  <ol> 
    <li>Select "View Problems" on the navigation bar. </li> 
  </ol> 
  <h3><a name="_Toc132145334">Viewing Problem Information</a></h3> 
  <p>To view specific information for a problem entry:</p> 
  <p>
    <li>Left-click on a particular problem entry on the "View Problems" page.</p> 
  <p>
    <li>A new page will load with specific problem information.</p> 
  <h3><a name="_Toc132145335">Submitting Completed Problems</a></h3> 
  <p>For students to submit completed problems:</p> 
  <ol>
    <li>View specific information for a particular problem by left-clicking on the problem in a list.</li> 
    <li>In the problem information, there is an option to submit the problem via the "Submit Solution" buttons. Press the "Submit Solution" button.</li>    <li>A box will appear with fields to fill out. Fill out the fields with answers.</li> 
    <li>Press the "Submit" button inside the box. </li> 
  </ol>
  <a name="viewsolution"></a>
  <h3><a name="_Toc132145336">Creating New Generation (Breeding)</a></h3> 
  <p>To view a particular generation:</p> 
  <ol>
    <li>View a particular problem's information by left-clicking on a problem in a list.</li> 
    <li>A list of generations will appear for the problem. Choose the desired generation to view by left-clicking on it.</li>
    <li>Select certain plants by invoking methods described below.</li> 
    <li>Press the "Cross Highlighted Plants" button.</li>
  </ol> 
  <p>If the breeding history fraction is less or equal to one (i.e. 30/100, 20/25, but not 25/25), then the creation of a new generation is allowed. Clicking on a generation listing will lead to generation pages that allow for the crossing to occur.</p> 
  <p>A generation page consists of:</p> 
  <ul>
    <li>A plant shelf filled with potted plants, denoting a field of plants (top left-side)</li>
    <li>Two histograms denoting the two traits (top right-side)</li> 
    <li>Information on highlighted plants, both individual and aggregative information (bottom left-side)</li> 
    <li>Legends explaining the colors and plant denotations (bottom right-side)</li> 
  </ul>
  <p>The student will be able to do the following in order to perform a crossing:</p> 
  <ul>
    <li>Hovering over particular plants on the plant shelf in order to see the measures of each trait for the plant.</li> 
    <li>Selecting particular plants on the plant shelf to breed by clicking on the particular plant. This must be done in order to successfully perform a cross. Students can also select/deselect plants that have been selected via the histograms by pressing the "Select/Deselect Color Plants" button. Students can also remove plants from the highlighted list by either the information table or clicking on the plant on the plant shelf.</li> 
    <li>Choosing plants from previous generations by selecting which generation to view. This is done by the dropdown menu on top of the plant shelf.</li> 
    <li>Hovering over particular bars on a histogram in order to see the numbers of plants and ranges represented by the bar.</li> 
    <li>Selecting particular bars on a histogram by clicking on the bar. This will highlight the plants inside the bars on the plant shelf. The student can use Shift and Ctrl to select groups of histogram bars, much like the functional equivalent in a Windows operating system.</li> 
    <li>Selecting particular bars on a histogram by dragging a selection box over the desired bars. This is also similar to the Windows functionality of click-and-dragging a selection box to select several files.</li> 
    <li>Viewing specific information about highlighted plants. Students will be able to see a highlighted plant's generation and trait measures. There is also information about the mean and variance of the highlighted plants as an aggregate.</li> 
  </ul>
  <h1><a name="_Toc132145337">Page Information</a></h1> 
  <h2><a name="_Toc132145338">General Page Attributes</a></h2> 
  <a name="help"></a>
  <h3><a name="_Toc132145339">Help</a></h3> 
  <p>This link on the upper-right corner will lead to a help page that corresponds with the current page the user is viewing. A help page has information on functions and attributes for the page, as well as access to other help files.</p> 
  <h3><a name="_Toc132145341">LOGOUT</a></h3> 
  <p>This link on the upper-right corner will allow a logged user to log out of his/her account. After clicking the link, the user will be redirected to the login page. This option does not appear when no account is active.</p> 
  <a name="aboutxgene360"></a>
  <h3><a name="_Toc132145342">About XGene 360</a></h3> 
  <p>This link on the lower-left corner will lead to a page describing the application in brief. This is for the curious.</p> 
  <a name="aboutteam7"></a>
  <h3><a name="_Toc132145343">About Team 7</a></h3> 
  <p>This link on the lower-left corner will lead to a page listing the names of the developers of XGene 360, Team 7.</p> 
  <h2><a name="_Toc132145344">Login Page</a></h2> 
  <h3><a name="_Toc132145345">Login Fields</a></h3> 
  <table class="format" width="100%"> 
    <tr> 
      <td width="200"><p><i>CWL Username</i></p></td> 
      <td><p>The CWL username associated with each account.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Password</i></p></td> 
      <td><p>The password associated with the CWL username entered above.</p></td> 
    </tr> 
  </table> 
  <a name="viewproblem"></a>
  <a name="viewproblems"></a>
  <h2><a name="_Toc132145346">View Problem(s)</a></h2> 
  <h3><a name="_Toc132145347">Problem Fields</a></h3> 
  <table class="format" width="100%" ID="Table1"> 
    <tr> 
      <td width="200"><p><i>Problem</i></p></td> 
      <td><p>This field denotes the name of the problem.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Description</i></p></td> 
      <td><p>This field is the description of the problem.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Course</i></p></td> 
      <td><p>The course that the problem is associated with.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Breeding History</i></p></td> 
      <td><p>This field denotes the ratio of number of crossings completed over the maximum number of crossings allowed.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>First Trait Name</i></p></td> 
      <td><p>This field denotes the name of one of the traits to be specified.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Second Trait Name</i></p></td> 
      <td><p>This field denotes the name of one of the traits to be specified.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Parent A Mean</i></p></td> 
      <td><p>The mean value of the first parent for one trait. (Not to be confused with first trait)</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Parent B Mean</i></p></td> 
      <td><p>The mean value of the second parent for one trait. (Not to be confused with second trait)</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Parent A SD</i></p></td> 
      <td><p>The standard deviation value of the first parent for one trait. (Not to be confused with first trait)</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Parent B SD</i></p></td> 
      <td><p>The standard deviation value of the second parent for one trait. (Not to be confused with second trait)</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Unit</i></p></td> 
      <td><p> This field denotes the unit for a trait.</p></td> 
    </tr> 
  </table> 
  <h3><a name="_Toc132145348">Histograms</a></h3> 
  <p>The two small histograms are a representation of the histograms for the first and second trait for that particular crossing.</p> 
  <h3><a name="_Toc132145349">Submit Solution</a></h3> 
  <p>This button is displayed on the left side, above and below the table of data. Pressing this button will submit the solution for marking. </p> 
  <a name="viewgeneration"></a>
  <h2><a name="_Toc132145350">View Generation</a></h2> 
  <h3><a name="_Toc132145351">Generation</a></h3> 
  <p>This field on the upper left of the plant shelf denotes which generation the user is viewing at the moment.</p> 
  <h3><a name="_Toc132145352">Select/Deselect Colored Plants</a></h3> 
  <p>This button, when pressed, allows the user to select or deselect plants that have been selected from the histograms.</p> 
  <h3><a name="_Toc132145353">Cross Highlighted Plants</a></h3> 
  <p>This button, when pressed, allows the user to cross the plants that have been highlighted on the plant shelf. A highlighted plant will have a changed background.</p> 
  <h3><a name="_Toc132145354">Highlighted Plant Information</a></h3> 
  <p>These are the tables that describe the attributes of the plants that have been highlighted on the plant shelf. A highlighted plant will have a changed background.</p> 
  <h3><a name="_Toc132145355">Individual Plants Fields</a></h3> 
  <table class="format" width="100%" ID="Table2"> 
    <tr> 
      <td width="200"><p><i>Generation</i></p></td> 
      <td><p>This field denotes the generation of the plant.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>First Trait</i></p></td> 
      <td><p>This field denotes value of the first trait for the plant.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Second Trait</i></p></td> 
      <td><p>This field denotes value of the second trait for the plant.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Remove</i></p></td> 
      <td><p>This button allows the user to remove the plant from the table</p></td> 
    </tr> 
  </table> 
  <h3><a name="_Toc132145356">All Plants Fields</a></h3> 
  <table class="format" width="100%" ID="Table3"> 
  <tr> 
      <td width="200"><p><i>Trait</i></p></td> 
      <td><p>This field denotes the trait type.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Overall Mean</i></p></td> 
      <td><p>This field denotes the aggregate mean of all the highlighted plants.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Overall SD</i></p></td> 
      <td><p>This field denotes the aggregate standard deviation of all the highlighted plants.</p></td> 
    </tr> 
  </table> 
  <h3><a name="_Toc132145357">Remove All Highlighted Plants</a></h3> 
  <p>This button, when pressed, allows the user to delete all the highlighted plants from the highlighted plant tables.</p> 
  <h3><a name="_Toc132145358">Plant Shelf Attributes</a></h3> 
  <table class="format" width="100%" ID="Table4"> 
    <tr> 
      <td width="200"><p><i>Pot</i></p></td> 
      <td><p>The pot denotes whether the plant has been selected from the histogram. If it is not selected, the pot will be a faded green. If selected by the first trait histogram, the pot will be blue. If selected by the second trait histogram, the pot will be red.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Plant</i></p></td> 
      <td><p>The plant is made up of two different types of leafs, one on the left and on the right. The left leaf describes the first trait and the right leaf describes the second trait.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Leaf</i></p></td> 
      <td><p>The size of the leaf denotes the position of the plant in respects to the histogram. A larger leaf can be found on the right-side of the histogram. A smaller can be found on the left-side of the histogram.</p></td> 
    </tr> 
  </table> 
</div> 