<div> 
  <h1><a name="_Toc132145223">How to Use XGene 360</a></h1> 
  <a name="index"></a>
  <h2><a name="_Toc132145224">General Information</a></h2> 
  <a name="login"></a>
  <h3><a name="_Toc132145225">Login</a></h3> 
  <p>To login to the application:</p> 
  <ol> 
    <li>Enter a CWL username.</li> 
    <li>Enter a password associated with the CWL username.</li> 
    <li>Press the "Login" button.</li> 
    <li>If the user is valid, the user will log into their account.</li> 
    <li>If the user is not valid, an error message will be produced and the user will be prompted to enter the information again.</li> 
  </ol> 
  <p>Only users with valid UBC CWL account are allowed to access the application.</p>
  <p>If user desires to have access to the application, the user will have to contact either a professor or site administrator of the application.</p> 
  <a name="logout"></a>
  <h3><a name="_Toc132145226">Logout</a></h3> 
  <p>To logout of the application while logged in:</p> 
  <ol> 
    <li>
     Click the "LOGOUT" link on the upper-right corner of the page. </li> 
    <li>
     The user will be logged out and brought back to the login page.</li> 
  </ol> 
  <p>Note that the user can log out at any time while logged in.</p> 
  <a name="changepassword"></a>
  <p>If the confirmation does not match, an error message will be produced and the user will be prompted to fill the correct information.</p> 
  <h3><a name="_Toc132145228">Navigation Bar</a></h3> 
  <p>The navigation bar on the top will hold links to relevant pages such as managing courses or viewing problems.</p> 
  <h3><a name="_Toc132145229">Sorting</a></h3> 
  <p>Any list of data has the capability of sorting the contents alphabetically and numerically by a header name. For example, a listing of problems can be sorted by the problem name, course that is associated with the problem, starting date, due date and breeding history.</p> 
  <p>To be able to sort data by a header type, just click on the header (which is displayed as a link). An arrow will appear on the right of the header name to indicate whether the sort is ascending (up arrow) or descending (down arrow). To toggle between ascending and descending, simply click the header name again. </p> 
  <h3><a name="_Toc132145230">Selecting</a></h3> 
  <p>A specific entry can be selected from a list of entry data in several ways:</p> 
  <ul>
  <li>
Having the cursor hover over an entry may show that the entry is a link. If the link is selected, the user will be led to a page containing specific information about that particular entry</li> 
  <li>
For most lists of data, the rightmost column will be a column of checkboxes. The checkboxes can be used to select several entries in order to perform operations such as deleting several courses. The header checkbox allows the user to select or deselect all entry checkboxes.</li> 
</ul>
  <p><a name="_Toc132145231">Problems Management</a></p> 
  <p>Problems are the heart of the application. This is where the professor can assign students a group of plants for the student to breed and solve the problem.</p> 
  <h3><a name="_Toc132145232">Viewing Problems Listing</a></h3> 
  <p>To view a list of problems:</p> 
  <ol> 
    <li>
     Select "View Problems" on the navigation bar. </li> 
  </ol> 
  <h3><a name="_Toc132145233">Viewing Problem Information</a></h3> 
  <p>To view specific information for a problem entry:</p> 
  <ol>


<li>Left-click on a particular problem entry on the "View Problems" page.</li> 
  <li>
A new page will load with specific problem information.</li>
</ol> 
  <h3><a name="_Toc132145234">Viewing Submitted Problems</a></h3> 
  <p>To view a student's particular submitted problem:</p> 
  <ol>
<li>

Find a button labeled "View Submitted" on the "View Problems" page that will lead to information about problem solutions. </li> 
  <li>
Click on the button for the problem entry in the list.</li></ol> 
  <h2><a name="_Toc132145235">Students Management</a></h2> 
  <p>Students are the users who will be solving the problems in the application.</p> 
  <h3><a name="_Toc132145236">Viewing Students Listing</a></h3> 
  <p>To view a list of students:</p> 
  <ol>
<li>

Select "View Students" on the navigation bar. </li>
</ol> 
  <h3><a name="_Toc132145237">Viewing Student Information</a></h3> 
  <p>To view specific information for a student entry:</p> 
  <ol> 
    <li>
     Left-click on a particular course entry on the "View Students" page.</li> 
    <li>
     A new page will load with specific student information.</li> 
  </ol> 
  <h1 align=left style='text-align:left'><a name="_Toc132145238">
Page Information</a></h1> 
  <h2><a name="_Toc132145239">General Page Attributes</a></h2> 
  <a name="help"></a>
  <h3><a name="_Toc132145240">Help</a></h3> 
  <p>This link on the upper-right corner will lead to a help page that corresponds with the current page the user is viewing. A help page has information on functions and attributes for the page, as well as access to other help files.</p> 
  <h3><a name="_Toc132145242">LOGOUT</a></h3> 
  <p>This link on the upper-right corner will allow a logged user to log out of his/her account. After clicking the link, the user will be redirected to the login page. This option does not appear when no account is active.</p> 
  <a name="aboutxgene360"></a>
  <h3><a name="_Toc132145243">About XGene 360</a></h3> 
  <p>This link on the lower-left corner will lead to a page describing the application in brief. This is for the curious.</p> 
  <a name="aboutteam7"></a>
  <h3><a name="_Toc132145244">About Team 7</a></h3> 
  <p>This link on the lower-left corner will lead to a page listing the names of the developers of XGene 360, Team 7.</p> 
  <h2><a name="_Toc132145245">Login Page</a></h2> 
  <h3><a name="_Toc132145246">Login Fields</a></h3> 
  <table class="format" width="100%" ID="Table3">
    <tr> 
      <td width="200"><p><i>CWL Username</i></p></td> 
      <td><p>The CWL username associated with each account.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Password</i></p></td> 
      <td><p>The password associated with the CWL username entered above.</p></td> 
    </tr> 
  </table> 
  <b><i><br clear=all style='page-break-before:always'> 
  </i></b> 
  <a name="managecourses"></a>
  <a name="viewcourse"></a>
  <h2><a name="_Toc132145247">View Course(s) Page</a></h2> 
  <h3><a name="_Toc132145248">Course Fields</a></h3> 
    <table class="format" width="100%" ID="Table1">    <tr> 
      <td width="200"><p><i>Course Name</i></p></td> 
      <td><p>This field denotes the name of the course. (i.e. BIOL 101)</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Description</i></p></td> 
      <td><p>This field is the description of the course. (i.e. "Introduction to Biology") The description field is limited to 250 characters, and the number of characters will be indicated by the world count field below the description field.&nbsp; </p></td> 
    </tr> 
  </table> 
  <a name="manageproblems"></a>
  <a name="viewproblem"></a>
  <a name="viewprogress"></a>
  <a name="viewsolutions"></a>
  <h2><a name="_Toc132145249">View Problem(s) Page</a></h2> 
  <h3><a name="_Toc132145250">Problem Fields</a></h3> 
    <table class="format" width="100%" ID="Table2">    <tr> 
      <td width="200"><p><i>Problem Name</i></p></td> 
      <td><p>This field denotes the name of the problem.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Problem Description</i></p></td> 
      <td><p>This field is the description of the problem. The description field is limited to 250 characters, and the number of characters will be indicated by the world count field below the description field.&nbsp; </p></td> 
    </tr> 
    <tr> 
      <td><p><i>Course</i></p></td> 
      <td><p>The course that the problem is associated with.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>First Trait Name</i></p></td> 
      <td><p>This field denotes the name of one of the traits to be specified.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Second Trait Name</i></p></td> 
      <td><p>This field denotes the name of one of the traits to be specified.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Max # of Crosses</i></p></td> 
      <td><p>This field restricts the student to a certain number of crossings allowed.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Offspring per Cross</i></p></td> 
      <td><p>This field denotes how many offspring should be produced with every crossing.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Displayed Plants per Cross</i></p></td> 
      <td><p>This field denotes how many plants from each crossing will be displayed on screen.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Range</i><i> of Acceptance</i></p></td> 
      <td><p>This is percentage that denotes how far the student's numerical solutions can be from the actual solution to be considered correct.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Parent 1 Mean</i></p></td> 
      <td><p>The mean value of the first parent for one trait. (Not to be confused with first trait)</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Parent 2 Mean</i></p></td> 
      <td><p>The mean value of the second parent for one trait. (Not to be confused with second trait)</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Environmental Variance</i></p></td> 
      <td><p>This field denotes the environmental variance.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Number of Genes</i></p></td> 
      <td><p>This field denotes the number of genes.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Unit</i></p></td> 
      <td><p>This field denotes the unit for a trait.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Histogram</i><i> Range</i></p></td> 
      <td><p>This is a percentage that denotes the histogram's range on the x-axis.</p></td> 
    </tr> 
  </table> 
  <h3><a name="_Toc132145251"># Students (Submitted/Total)</a></h3> 
  <p>This listing header denotes the ratio of the number of students who submitted solutions over the overall number of students assigned to the problem.</p> 
  <h3><a name="_Toc132145252">View Submitted</a></h3> 
  <p>This button allows a user to view a list of students who have submitted problems.</p> 
  <a name="managestudents"></a>  
  <a name="viewstudent"></a>
  <h2><a name="_Toc132145253">View Student(s)</a></h2> 
  <h3><a name="_Toc132145254">Student Fields</a></h3> 
    <table class="format" width="100%" ID="Table4">    <tr> 
      <td width="200"><p><i>First Name</i></p></td> 
      <td><p>This field denotes the first name of the student.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>Last Name</i></p></td> 
      <td><p>This field denotes the last name of the student.</p></td> 
    </tr> 
    <tr> 
      <td><p><i>CWL Username</i></p></td> 
      <td><p>This field denotes the CWL username associated with the student.</p></td> 
    </tr> 
  </table> 
</div> 