    <div>
      <h1><a name="_Toc132145128">How to Use XGene 360</a></h1>
      <a name="index"></a>
      <h2><a name="_Toc132145129">General Information</a></h2>
      <a name="login"></a>
      <h3><a name="_Toc132145130">Login</a></h3>
      <p>To login to the application:</p>
      <ol>
        <li>
          Enter a username.</li>
        <li>
          Enter a password.</li>
        <li>
          Choose between logging in either XGene 360 or GreenGene.</li>
        <li>
          Press the ‘Login’ button.</li>
        <li>
          If the user is valid, the user will log into their account.</li>
        <li>
          If the user is not valid, an error message will be produced and the user will 
          be prompted to enter the information again.</li>
      </ol>
      <p>There is an additional option in the login box to login to either XGene 360 or 
        GreenGene. If the user selected the GreenGene radio button, the user should be 
        a valid GreenGene user. By default the user will be logged into XGene 360.</p>
      <p>If user desires to create an account, the user will have to contact the 
        administrator of the application.</p>
      <a name="logout"></a>
      <h3><a name="_Toc132145131">Logout</a></h3>
      <p>To logout of the application while logged in:</p>
      <ol>
        <li>
          Click the ‘LOGOUT’ link on the upper-right corner of the page.
        </li>
        <li>
          The user will be logged out and brought back to the login page.</li>
      </ol>
      <p>Note that the user can log out at any time while logged in.</p>
      <a name="changepassword"></a>
      <h3><a name="_Toc132145132">Change Password</a></h3>
      <p>Users have the capacity to change their own passwords. To change passwords:</p>
      <ol>
        <li>
          Click on the ‘Change Password’ link on the upper-right corner of the page.
        </li>
        <li>
          Enter the old password.</li>
        <li>
          Enter the new password.</li>
        <li>
          Enter the new password again for confirmation.
        </li>
        <li>
          Press the ‘Update’ button.</li>
      </ol>
      <p>If the confirmation does not match, an error message will be produced and the 
        user will be prompted to fill the correct information.</p>
      <h3><a name="_Toc132145133">Navigation Bar</a></h3>
      <p>The navigation bar on the top will hold links to relevant pages such as 
        managing courses or viewing problems.</p>
      <h3><a name="_Toc132145134">Sorting</a></h3>
      <p>Any list of data has the capability of sorting the contents alphabetically and 
        numerically by a header name. For example, a listing of problems can be sorted 
        by the problem name, course that is associated with the problem, starting date, 
        due date and breeding history.</p>
      <p>To be able to sort data by a header type, just click on the header (which is 
        displayed as a link). An arrow will appear on the right of the header name to 
        indicate whether the sort is ascending (up arrow) or descending (down arrow). 
        To toggle between ascending and descending, simply click the header name again.
      </p>
      <h3><a name="_Toc132145135">Selecting</a></h3>
      <p>A specific entry can be selected from a list of entry data in several ways:</p>
      <ul>
        <li>
          Having the cursor hover over an entry may show that the entry is a link. If the 
          link is selected, the user will be led to a page containing specific 
          information about that particular entry</li>
        <li>
          For most lists of data, the rightmost column will be a column of checkboxes. 
          The checkboxes can be used to select several entries in order to perform 
          operations such as deleting several courses. The header checkbox allows the 
          user to select or deselect all entry checkboxes.</li>
      </ul>
      <h2><a name="_Toc132145136">Courses Management</a></h2>
      <p>Courses are used to group together sets of problems. Users can also be 
        assigned to a course as a way to group users together. For example, there can 
        be a BIOL 112 course with ten students, or a BIOL 433 course with two problems 
        and six students.</p>
      <h3><a name="_Toc132145137">Viewing Courses Listing</a></h3>
      <p>To view a list of courses:</p>
      <ol>
        <li>
          Select ‘Manage Courses’ on the navigation bar.
        </li>
      </ol>
      <h3><a name="_Toc132145138">Creating New Course</a></h3>
      <p>To create a new course:</p>
      <ol>
        <li>
          Click on the ‘Create New Course’ button on the ‘Manage Courses’ page.
        </li>
        <li>
          A box will open with course information fields.</li>
        <li>
          Fill the fields in the box.
        </li>
        <li>
          Press the ‘Create' button inside the box, or press ‘Reset’ to reset fields.</li>
      </ol>
      <h3><a name="_Toc132145139">Deleting Existing Course(s)</a></h3>
      <p>To delete existing courses:</p>
      <ol>
        <li>
          Select courses to be deleted via checkboxes on the ‘Manage Courses’ page.</li>
        <li>
          Press the ‘Delete Selected Courses’ button.</li>
      </ol>
      <h3><a name="_Toc132145140">Viewing Course Information</a></h3>
      <p>To view specific information for a course entry:</p>
      <ol>
        <li>Left-click on a particular course entry on the ‘Manage Courses’ page.</li>
        <li>
        A new page will load with specific course information.</li>
      </ol>
      <h3><a name="_Toc132145141">Editing Course Information</a></h3>
      <p>To edit course information:</p>
      <ol>
        <li>
          View specific course information by left-clicking on a particular entry on the 
          ‘Manage Courses’ page.</li>
        <li>
          Edit the fields that allow editing.</li>
        <li>
          Press the ‘Update’ button.</li>
      </ol>
      <p><a name="_Toc132145142"> class=Heading2Char> style='font-size:14.0pt'>Problems 
          Management</a></p>
      <p>Problems are the heart of the application. This is where the professor can 
        assign students a group of plants for the student to breed and solve the 
        problem.</p>
      <h3><a name="_Toc132145143">Viewing Problems Listing</a></h3>
      <p>To view a list of problems:</p>
      <ol>
        <li>
          Select ‘Manage Problems’ on the navigation bar.
        </li>
      </ol>
      <h3><a name="_Toc132145144">Creating New Problem</a></h3>
      <p>To create a new problem:</p>
      <ol>
        <li>
          Click on the ‘Create New Problem’ button on the ‘Manage Problems’ page.
        </li>
        <li>
          A new page will appear with problem information fields.</li>
        <li>
          Fill the fields in the box.
        </li>
        <li>
          Press the ‘Create' button, or press ‘Reset’ to reset fields.</li>
      </ol>
      <h3><a name="_Toc132145145">Deleting Selected Problem(s)</a></h3>
      <p>To delete existing problems:</p>
      <ol>
        <li>
          Select problems to be deleted via checkboxes on the ‘Manage Problems’ page.</li>
        <li>
          Press the ‘Delete Selected Problems’ button.</li>
      </ol>
      <h3><a name="_Toc132145146">Viewing Problem Information</a></h3>
      <p>To view specific information for a problem entry:</p>
      <ol>
        <li>
          Left-click on a particular problem entry on the ‘Manage Problems’ page.</li>
        <li>
          A new page will load with specific problem information.</li>
      </ol>
      <h3><a name="_Toc132145147">Editing Problem Information</a></h3>
      <p>To edit course information:</p>
      <ol>
        <li>
          View specific problem information by left-clicking on a particular entry on the 
          ‘Manage Problem’ page.</li>
        <li>
          Edit the fields that allow editing.</li>
        <li>
          Press the ‘Update’ button.</li>
      </ol>
      <h3><a name="_Toc132145148">Viewing Submitted Problems</a></h3>
      <p>To view a student’s particular submitted problem:</p>
      <ol>
        <li>
          Find a button labeled ‘View Submitted’ on the ‘Manage Problems’ page that will 
          lead to information about problem solutions.
        </li>
        <li>
          Click on the button for the problem entry in the list.</li>
      </ol>
      <h2><a name="_Toc132145149">Professors Management</a></h2>
      <p>Professors are able to create problems and assign them to students and TAs. 
        Professors can also create new courses, professors and users.</p>
      <h3><a name="_Toc132145150">Viewing Professors Listing</a></h3>
      <p>To view a list of professors:</p>
      <ol>
        <li>
          Select ‘Manage Professors’ on the navigation bar.
        </li>
      </ol>
      <h3><a name="_Toc132145151">Creating New Professor</a></h3>
      <p>To create a new professor:</p>
      <ol>
        <li>
          Click on the ‘Create New’ button on the ‘Manage Professors’ page.
        </li>
        <li>
          A box will open with professor information fields.</li>
        <li>
          Fill the fields in the box.
        </li>
        <li>
          Press the ‘Create' button inside the box, or press ‘Reset’ to reset fields.</li>
      </ol>
      <h3><a name="_Toc132145152">Deleting Existing Professor(s)</a></h3>
      <p>To delete existing professor(s):</p>
      <ol>
        <li>
          Select courses to be deleted via checkboxes on the ‘Manage Professors’ page.</li>
        <li>
          Press the ‘Delete Selected’ button.</li>
      </ol>
      <h3><a name="_Toc132145153">Viewing Professor Information</a></h3>
      <p>To view specific information for a professor entry:</p>
      <ol>
        <li>
          Left-click on a particular course entry on the ‘Manage Professors’ page.</li>
        <li>
          A new page will load with specific professor information.</li>
      </ol>
      <h3><a name="_Toc132145154">Editing Professor Information</a></h3>
      <p>To edit professor information:</p>
      <ol>
        <li>
          View specific professor information by left-clicking on a particular entry on 
          the ‘Manage Professors’ page.</li>
        <li>
          Edit the fields that allow editing.</li>
        <li>
          Press the ‘Update’ button.</li>
      </ol>
      <p>Professors can be edited when their information is viewed. Users can edit the 
        fields and then press the ‘Update’ button.</p>
      <h3><a name="_Toc132145155">Importing Professors from External List</a></h3>
      <p>Users are able to import professor accounts by providing a .csv file. A .csv 
        file is essentially a file which lists professor information to be inserted 
        into the application. Professor accounts are separated by newlines (Enter) and 
        the fields of a professor are separated by commas.</p>
      <p>To import professor data:</p>
      <ol>
        <li>
          Press the ‘Import List’ button.
        </li>
        <li>
          A box will appear for importing data.</li>
        <li>
          Click ‘Browse’ to select a local file to load.
        </li>
        <li>
          After selecting the file, press the ‘Import’ button to import the file.</li>
      </ol>
      <p>There is an option for the professor to be able to access the GreenGene 
        application. To be able to do so, the user can check the box beside the 
        sentence ‘Allow user to access GreenGene site’. The user will be prompted to 
        choose a GreenGene course to insert the professor in. The course selection is a 
        mandatory step.</p>
      <h3><a name="_Toc132145156">Exporting Selected Professors to External List</a></h3>
      <p>Users are able to export professor accounts into new local .csv files.
      </p>
      <p>To export professor(s):</p>
      <ol>
        <li>
          Select professors from the list via the checkboxes on the left.
        </li>
        <li>
          Press the ‘Exported Selected’ button.</li>
        <li>
          After pressing the button, there will be a prompt for downloading the file into 
          a local folder.</li>
      </ol>
      <h3><a name="_Toc132145157">Assigning Professor(s) to a Course</a></h3>
      <p>To assign professors to a course:</p>
      <ol>
        <li>
          Select professors from the list via the checkboxes on the left.
        </li>
        <li>
          Select a course in the dropdown menu on the top-right of the professor listing.
        </li>
        <li>
          Press the ‘Assign’ button.</li>
      </ol>
      <h2><a name="_Toc132145158">Teaching Assistants (TAs) Management</a></h2>
      <p>TAs are able to view lists of courses, problems and students. They can also 
        view submitted problems.</p>
      <h3><a name="_Toc132145159">Viewing TAs Listing</a></h3>
      <p>To view a list of TAs:</p>
      <ol>
        <li>
          Select ‘Manage TAs’ on the navigation bar.
        </li>
      </ol>
      <h3><a name="_Toc132145160">Creating New TA</a></h3>
      <p>To create a new TA:</p>
      <ol>
        <li>
          Click on the ‘Create New’ button on the ‘Manage TAs’ page.
        </li>
        <li>
          A box will open with TA information fields.</li>
        <li>
          Fill the fields in the box.
        </li>
        <li>
          Press the ‘Create' button inside the box, or press ‘Reset’ to reset fields.</li>
      </ol>
      <h3><a name="_Toc132145161">Deleting Existing TA(s)</a></h3>
      <p>To delete existing TA(s):</p>
      <ol>
        <li>
        Select courses to be deleted via checkboxes on the ‘Manage TAs’ page.</li>
      <li>
        Press the ‘Delete Selected’ button.</li> </ol>
        <h3><a name="_Toc132145162">Viewing TA Information</a></h3>
        <p>To view specific information for a TA entry:</p>
       <ol>
      <li>
        Left-click on a particular course entry on the ‘Manage TAs’ page.</li>
      <li>
        A new page will load with specific TA information.</li>
      </ol>
      <h3><a name="_Toc132145163">Editing TA Information</a></h3>
      <p>To edit TA information:</p>
      <ol>
        <li>
          View specific TA information by left-clicking on a particular entry on the 
          ‘Manage TAs’ page.</li>
        <li>
          Edit the fields that allow editing.</li>
        <li>
          Press the ‘Update’ button.</li>
      </ol>
      <p>TAs can be edited when their information is viewed. Users can edit the fields 
        and then press the ‘Update’ button.</p>
      <h3><a name="_Toc132145164">Importing TAs from External List</a></h3>
      <p>Users are able to import TA accounts by providing a .csv file. A .csv file is 
        essentially a file which lists TA information to be inserted into the 
        application. TA accounts are separated by newlines (Enter) and the fields of a 
        TA are separated by commas.</p>
      <p>To import TA data:</p>
      <ol>
        <li>
          Press the ‘Import List’ button.
        </li>
        <li>
          A box will appear for importing data.</li>
        <li>
          Click ‘Browse’ to select a local file to load.
        </li>
        <li>
          After selecting the file, press the ‘Import’ button to import the file.</li>
      </ol>
      <p>There is an option for the TA to be able to access the GreenGene application. 
        To be able to do so, the user can check the box beside the sentence ‘Allow user 
        to access GreenGene site’. The user will be prompted to choose a GreenGene 
        course to insert the TA in. The course selection is a mandatory step.</p>
      <h3><a name="_Toc132145165">Exporting Selected TAs to External List</a></h3>
      <p>Users are able to export TA accounts into new local .csv files.
      </p>
      <p>To export TA(s):</p>
      <ol>
        <li>
          Select TAs from the list via the checkboxes on the left.
        </li>
        <li>
          Press the ‘Exported Selected’ button.</li>
        <li>
          After pressing the button, there will be a prompt for downloading the file into 
          a local folder.</li>
      </ol>
      <h3><a name="_Toc132145166">Assigning TA(s) to a Course</a></h3>
      <p>To assign TAs to a course:</p>
      <ol>
        <li>
          Select TAs from the list via the checkboxes on the left.
        </li>
        <li>
          Select a course in the dropdown menu on the top-right of the TA listing.
        </li>
        <li>
          Press the ‘Assign’ button.</li>
      </ol>
      <h2><a name="_Toc132145167">Students Management</a></h2>
      <p>Students are the users who will be solving the problems in the application.</p>
      <h3><a name="_Toc132145168">Viewing Students Listing</a></h3>
      <p>To view a list of students:</p>
      <ol>
        <li>
          Select ‘Manage Students’ on the navigation bar.
        </li>
      </ol>
      <h3><a name="_Toc132145169">Creating New Student</a></h3>
      <p>To create a new student:</p>
      <ol>
        <li>
          Click on the ‘Create New’ button on the ‘Manage Students’ page.
        </li>
        <li>
          A box will open with student information fields.</li>
        <li>
          Fill the fields in the box.
        </li>
        <li>
          Press the ‘Create' button inside the box, or press ‘Reset’ to reset fields.</li>
      </ol>
      <h3><a name="_Toc132145170">Deleting Existing Student(s)</a></h3>
      <p>To delete existing student(s):</p>
      <ol>
        <li>
          Select courses to be deleted via checkboxes on the ‘Manage Students’ page.</li>
        <li>
          Press the ‘Delete Selected’ button.</li>
      </ol>
      <h3><a name="_Toc132145171">Viewing Student Information</a></h3>
      <p>To view specific information for a student entry:</p>
      <ol>
        <li>
          Left-click on a particular course entry on the ‘Manage Students’ page.</li>
        <li>
          A new page will load with specific student information.</li>
      </ol>
      <h3><a name="_Toc132145172">Editing Student Information</a></h3>
      <p>To edit student information:</p>
      <ol>
        <li>
          View specific student information by left-clicking on a particular entry on the 
          ‘Manage Students’ page.</li>
        <li>
          Edit the fields that allow editing.</li>
        <li>
          Press the ‘Update’ button.</li>
      </ol>
      <p>Students can be edited when their information is viewed. Users can edit the 
        fields and then press the ‘Update’ button.</p>
      <h3><a name="_Toc132145173">Importing Students from External List</a></h3>
      <p>Users are able to import student accounts by providing a .csv file. A .csv 
        file is essentially a file which lists student information to be inserted into 
        the application. Student accounts are separated by newlines (Enter) and the 
        fields of a student are separated by commas.</p>
      <p>To import student data:</p>
      <ol>
        <li>
          Press the ‘Import List’ button.
        </li>
        <li>
          A box will appear for importing data.</li>
        <li>
          Click ‘Browse’ to select a local file to load.
        </li>
        <li>
          After selecting the file, press the ‘Import’ button to import the file.</li>
      </ol>
      <p>There is an option for the student to be able to access the GreenGene 
        application. To be able to do so, the user can check the box beside the 
        sentence ‘Allow user to access GreenGene site’. The user will be prompted to 
        choose a GreenGene course to insert the student in. The course selection is a 
        mandatory step.</p>
      <h3><a name="_Toc132145174">Exporting Selected Students to External List</a></h3>
      <p>Users are able to export student accounts into new local .csv files.
      </p>
      <p>To export student(s):</p>
      <ol>
        <li>
          Select students from the list via the checkboxes on the left.
        </li>
        <li>
          Press the ‘Exported Selected’ button.</li>
        <li>
          After pressing the button, there will be a prompt for downloading the file into 
          a local folder.</li>
      </ol>
      <h3><a name="_Toc132145175">Assigning Student(s) to a Problem</a></h3>
      <p>To assign students to a problem:</p>
      <ol>
        <li>
          Select students from the list via the checkboxes on the left.
        </li>
        <li>
          Select a problem in the dropdown menu on the top-right of the student listing.
        </li>
        <li>
          Press the ‘Assign’ button.</li>
      </ol>
      <h3><a name="_Toc132145176">Assigning Student(s) to All Problems in a Course</a></h3>
      <p>To assign students to all problems in a course:</p>
      <ol>
        <li>
          Select students from the list via the checkboxes on the left.
        </li>
        <li>
          Select a course in the dropdown menu on the top-right of the student listing.
        </li>
        <li>
          Press the ‘Assign’ button.</li>
      </ol>
      <h1><a name="_Toc132145177">Page Information</a></h1>
      <h2><a name="_Toc132145178">General Page Attributes</a></h2>
      <a name="help"></a>
      <h3><a name="_Toc132145179">Help</a></h3>
      <p>This link on the upper-right corner will lead to a help page that corresponds 
        with the current page the user is viewing. A help page has information on 
        functions and attributes for the page, as well as access to other help files.</p>
      <h3><a name="_Toc132145180">Change Password</a></h3>
      <p>This link on the upper-right corner will lead to a page that will allow you to 
        change the password of the user that is logged in. This option does not appear 
        when no account is active.</p>
      <h3><a name="_Toc132145181">LOGOUT</a></h3>
      <p>This link on the upper-right corner will allow a logged user to log out of 
        his/her account. After clicking the link, the user will be redirected to the 
        login page. This option does not appear when no account is active.</p>
      <a name="aboutxgene360"></a>
      <h3><a name="_Toc132145182">About XGene 360</a></h3>
      <p>This link on the lower-left corner will lead to a page describing the 
        application in brief. This is for the curious.</p>
      <a name="aboutteam7"></a>
      <h3><a name="_Toc132145183">About Team 7</a></h3>
      <p>This link on the lower-left corner will lead to a page listing the names of 
        the developers of XGene 360, Team 7.</p>
      <h2><a name="_Toc132145184">Login Page</a></h2>
      <h3><a name="_Toc132145185">Login Fields</a></h3>
      <table class="format" width="100%">
        <tr>
          <td width="200"><p><i>Username</i></p>
          </td>
          <td><p>The unique username associated with each account.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Password</i></p>
          </td>
          <td><p>The password associated with the username entered above.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>XGene 360/GreenGene radio buttons</i></p>
          </td>
          <td><p>This will allow the user to choose whether he/she wants to login to the 
              XGene 360 or GreenGene application. It is assumed that the user has a valid 
              account with the desired login type.</p>
          </td>
        </tr>
      </table>
      <a name="createproblem"></a>
      <a name="manageproblems"></a>
      <a name="viewproblem"></a>
      <a name="viewprogress"></a>
      <a name="viewsolutions"></a>
      <h2><a name="_Toc132145186">Manage/View Problem(s) Page</a></h2>
      <h3><a name="_Toc132145187">Problem Fields</a></h3>
      <table class="format" width="100%" ID="Table1">
        <tr>
          <td width="200"><p><i>Copy Problem From</i></p>
          </td>
          <td><p>Users are given the opportunity to copy previously created problem.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Problem Name</i></p>
          </td>
          <td><p>This field denotes the name of the problem.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Problem Description</i></p>
          </td>
          <td><p>This field is the description of the problem. The description field is 
              limited to 250 characters, and the number of characters will be indicated by 
              the world count field below the description field.&nbsp;
            </p>
          </td>
        </tr>
        <tr>
          <td><p><i>Course</i></p>
          </td>
          <td><p>The course that the problem is associated with.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Start Date</i></p>
          </td>
          <td><p>The starting date for the problem. The problem will not show until the 
              starting date has passed. The month, day, year, hour and minute can be 
              specified.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Due Date</i></p>
          </td>
          <td><p>The due date for the problem. The month, day, year, hour and minute can be 
              specified.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>First Trait Name</i></p>
          </td>
          <td><p>This field denotes the name of one of the traits to be specified.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Second Trait Name</i></p>
          </td>
          <td><p>This field denotes the name of one of the traits to be specified.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Max # of Crosses</i></p>
          </td>
          <td><p>This field restricts the student to a certain number of crossings allowed.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Offspring per Cross</i></p>
          </td>
          <td><p>This field denotes how many offspring should be produced with every 
              crossing.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Displayed Plants per Cross</i></p>
          </td>
          <td><p>This field denotes how many plants from each crossing will be displayed on 
              screen.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Range</i><i> of Acceptance</i></p>
          </td>
          <td><p>This is a percentage that denotes how far the student’s numerical solutions 
              can be from the actual solution to be considered correct.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Parent 1 Mean</i></p>
          </td>
          <td><p>The mean value of the first parent for one trait. (Not to be confused with 
              first trait)</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Parent 2 Mean</i></p>
          </td>
          <td><p>The mean value of the second parent for one trait. (Not to be confused with 
              second trait)</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Environmental Variance</i></p>
          </td>
          <td><p>This field denotes the environmental variance.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Number of Genes</i></p>
          </td>
          <td><p>This field denotes the number of genes.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Unit</i></p>
          </td>
          <td><p>This field denotes the unit for a trait.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Histogram</i><i> Range</i></p>
          </td>
          <td><p>This is a percentage that denotes the histogram’s range on the x-axis.</p>
          </td>
        </tr>
      </table>
      <h3><a name="_Toc132145188">Create New Problem</a></h3>
      <p>This button is displayed on the left side, above and below the table of data. 
        Pressing this button will open a new page that displays fields to fill in to 
        create a new data entry.
      </p>
      <h3><a name="_Toc132145189">Delete Selected Problems</a></h3>
      <p>This button is displayed on the left side, above and below the table of data. 
        Pressing this button will delete entries selected within the table.</p>
      <h3><a name="_Toc132145190"># Students (Submitted/Total)</a></h3>
      <p>This listing header denotes the ratio of the number of students who submitted 
        solutions over the overall number of students assigned to the problem.</p>
      <h3><a name="_Toc132145191">View Submitted</a></h3>
      <p>This button allows a user to view a list of students who have submitted 
        problems.</p>
      <a name="manageprofessors"></a>
      <a name="viewprofessor"></a>
      <h2><a name="_Toc132145192">Manage/View Professor(s)</a></h2>
      <h3><a name="_Toc132145193">Professor Fields</a></h3>
      <table class="format" width="100%" ID="Table2">
        <tr>
          <td width="200"><p><i>First Name</i></p>
          </td>
          <td><p>This field denotes the first name of the professor.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Last Name</i></p>
          </td>
          <td><p>This field denotes the last name of the professor.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Username</i></p>
          </td>
          <td><p>This field denotes the unique username associated with the professor.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Password</i></p>
          </td>
          <td><p>This field denotes the password associated with the professor</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Confirm Password</i></p>
          </td>
          <td><p>When creating a new professor, a confirmation is needed for the newly 
              entered password in case the password is incorrectly typed in.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Allow user to access GreenGene site</i></p>
          </td>
          <td><p>This checkbox, if selected, allows a professor to access the GreenGene site.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>GreenGene Course</i></p>
          </td>
          <td><p>If the above checkbox is selected, this field denotes the GreenGene course 
              associated with the professor.</p>
          </td>
        </tr>
      </table>
      <h3><a name="_Toc132145194">Create New</a></h3>
      <p>This button is displayed on the left side, above and below the table of data. 
        Pressing this button will open a box that displays fields to fill in to create 
        a new data entry.
      </p>
      <h3><a name="_Toc132145195">Import List</a></h3>
      <p>This button is displayed on the left side, above and below the table of data. 
        Pressing this button will open a box that displays fields to import a .csv 
        file. A .csv file is essentially a file which lists professor information to be 
        inserted into the application. Professor accounts are separated by newlines 
        (Enter) and the fields of a professor are separated by commas.</p>
      <h3><a name="_Toc132145196">Export Selected</a></h3>
      <p>This button is displayed on the left side, above and below the table of data. 
        Pressing this button will allow the exporting of selected professors into a 
        .csv file. This file is described in Import List.</p>
      <h3><a name="_Toc132145197">Delete Selected</a></h3>
      <p>This button is displayed on the left side, above and below the table of data. 
        Pressing this button will delete entries selected within the table.</p>
      <h3><a name="_Toc132145198">Assign selected to course:</a></h3>
      <p>This dropdown menu is displayed on the right side and above the table of data. 
        It allows the assignment of a course to selected professors.</p>
      <a name="managetas"></a>
      <a name="viewta"></a>
      <h2><a name="_Toc132145199">Manage/View TA(s)</a></h2>
      <h3><a name="_Toc132145200">TA Fields</a></h3>
      <table class="format" width="100%" ID="Table3">
        <tr>
          <td width="200"><p><i>First Name</i></p>
          </td>
          <td><p>This field denotes the first name of the TA.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Last Name</i></p>
          </td>
          <td><p>This field denotes the last name of the TA.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Username</i></p>
          </td>
          <td><p>This field denotes the unique username associated with the TA.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Password</i></p>
          </td>
          <td><p>This field denotes the password associated with the TA</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Confirm Password</i></p>
          </td>
          <td><p>When creating a new TA, a confirmation is needed for the newly entered 
              password in case the password is incorrectly typed in.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Allow user to access GreenGene site</i></p>
          </td>
          <td><p>This checkbox, if selected, allows a TA to access the GreenGene site.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>GreenGene Course</i></p>
          </td>
          <td><p>If the above checkbox is selected, this field denotes the GreenGene course 
              associated with the TA.</p>
          </td>
        </tr>
      </table>
      <h3><a name="_Toc132145201">Create New</a></h3>
      <p>This button is displayed on the left side, above and below the table of data. 
        Pressing this button will open a box that displays fields to fill in to create 
        a new data entry.
      </p>
      <h3><a name="_Toc132145202">Import List</a></h3>
      <p>This button is displayed on the left side, above and below the table of data. 
        Pressing this button will open a box that displays fields to import a .csv 
        file. A .csv file is essentially a file which lists TA information to be 
        inserted into the application. TA accounts are separated by newlines (Enter) 
        and the fields of a TA are separated by commas.</p>
      <h3><a name="_Toc132145203">Export Selected</a></h3>
      <p>This button is displayed on the left side, above and below the table of data. 
        Pressing this button will allow the exporting of selected TAs into a .csv file. 
        This file is described in Import List.</p>
      <h3><a name="_Toc132145204">Delete Selected</a></h3>
      <p>This button is displayed on the left side, above and below the table of data. 
        Pressing this button will delete entries selected within the table.</p>
      <h3><a name="_Toc132145205">Assign selected to course:</a></h3>
      <p>This dropdown menu is displayed on the right side and above the table of data. 
        It allows the assignment of a course to selected TAs.</p>
      <a name="managestudents"></a>
      <a name="viewstudent"></a>
      <h2><a name="_Toc132145206">Manage/View Student(s)</a></h2>
      <h3><a name="_Toc132145207">Student Fields</a></h3>
      <table class="format" width="100%" ID="Table4">
        <tr>
          <td width="200"><p><i>First Name</i></p>
          </td>
          <td><p>This field denotes the first name of the student.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Last Name</i></p>
          </td>
          <td><p>This field denotes the last name of the student.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Student Number</i></p>
          </td>
          <td><p>The field denotes the unique student number associated with the student.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Username</i></p>
          </td>
          <td><p>This field denotes the unique username associated with the student.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Password</i></p>
          </td>
          <td><p>This field denotes the password associated with the student</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Confirm Password</i></p>
          </td>
          <td><p>When creating a new student, a confirmation is needed for the newly entered 
              password in case the password is incorrectly typed in.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Allow user to access GreenGene site</i></p>
          </td>
          <td><p>This checkbox, if selected, allows a student to access the GreenGene site.</p>
          </td>
        </tr>
        <tr>
          <td><p><i>GreenGene Course</i></p>
          </td>
          <td><p>If the above checkbox is selected, this field denotes the GreenGene course 
              associated with the student.</p>
          </td>
        </tr>
      </table>
      <h3><a name="_Toc132145208">Create New</a></h3>
      <p>This button is displayed on the left side, above and below the table of data. 
        Pressing this button will open a box that displays fields to fill in to create 
        a new data entry.
      </p>
      <h3><a name="_Toc132145209">Import List</a></h3>
      <p>This button is displayed on the left side, above and below the table of data. 
        Pressing this button will open a box that displays fields to import a .csv 
        file. A .csv file is essentially a file which lists student information to be 
        inserted into the application. Student accounts are separated by newlines 
        (Enter) and the fields of a student are separated by commas.</p>
      <h3><a name="_Toc132145210">Export Selected</a></h3>
      <p>This button is displayed on the left side, above and below the table of data. 
        Pressing this button will allow the exporting of selected students into a .csv 
        file. This file is described in Import List.</p>
      <h3><a name="_Toc132145211">Delete Selected</a></h3>
      <p>This button is displayed on the left side, above and below the table of data. 
        Pressing this button will delete entries selected within the table.</p>
      <h3><a name="_Toc132145212">Choose type to assign:</a></h3>
      <p>This dropdown menu is displayed on the right side and above the table of data. 
        It chooses what type from a selection to assign to selected students.</p>
      <h3><a name="_Toc132145213">Assign to problem:</a></h3>
      <p>This dropdown menu is displayed on the right side and above the table of data. 
        It allows the assignment of a problem to selected students.</p>
      <h3><a name="_Toc132145214">Assign to course:</a></h3>
      <p>This dropdown menu is displayed on the right side and above the table of data. 
        It allows the assignment of all problems of a course to selected students.</p>
      <a name="managecourses"></a>
      <a name="viewcourse"></a>
      <h2><a name="_Toc132145215">Manage/View Course(s) Page</a></h2>
      <h3><a name="_Toc132145216">Course Fields</a></h3>
      <table class="format" width="100%" ID="Table5">
        <tr>
          <td width="200"><p><i>Course Name</i></p>
          </td>
          <td><p>This field will denote the name of the course. (i.e. BIOL 101)</p>
          </td>
        </tr>
        <tr>
          <td><p><i>Description</i></p>
          </td>
          <td><p>This field is the description of the course. (i.e. “Introduction to 
              Biology”) The description field is limited to 250 characters, and the number of 
              characters will be indicated by the world count field below the description 
              field.&nbsp;
            </p>
          </td>
        </tr>
      </table>
      <h3><a name="_Toc132145217">Create New Course</a></h3>
      <p>This button is displayed on the left side, above and below the table of data. 
        Pressing this button will open a box that displays fields to fill in to create 
        a new data entry.
      </p>
      <h3><a name="_Toc132145218">Delete Selected Courses</a></h3>
      <p>This button is displayed on the left side, above and below the table of data. 
        Pressing this button will delete entries selected within the table.</p>
    </div>